- hawtio-jboss/pom.xml
This fix contains a WAR with a minimal set up libraries needed for successfully deploying Hawtio (hawtio-jboss) on JBoss EAP 6.3.
> A partial fix for https://github.com/hawtio/hawtio/issues/1843 for hawtio-jboss WAR

- hawtio-web/src/main/webapp/lib/codemirror/mode/properties/properties.js
Codemirror was interpreting a backslash character anywhere in a line as a continuation character.
> ENTESB-2709 property keys are not displayed with correct color

- hawtio-system/src/main/java/io/hawt/web/UserServlet.java
You should check for a null ConfigManager before trying to access it to retrieve the 'authenticationEnabled' setting. In my environment (OSGi HTTP service), registering context parameters is disabled so the parameter will always be missing. This should not cause a NullPointerException when initializing the UserServlet.
> Check for null servlet context ConfigManager attribute

- hawtio-springboot/src/main/java/io/hawt/springboot/HawtioConfiguration.java
Removed the redirect from / to hawtio/index.html.
Spring boot users can add the registry.addViewController("/").setViewName("redirect:/hawtio/index.html"); in their own configuration if they need it. For most users this will only be a hassle if they do not want it.
> Removed redirect from / since this will take over the root of the project.

- hawtio-web/src/main/webapp/app/osgi/html/configurations.html
- hawtio-web/src/main/webapp/app/osgi/js/configurations.ts
This addresses issue #2014, in a rudimentary fashion.  The functionality is there to simply click a single button, and create a new managed service, with metatype information.
> added button to create managed service from a factory

- hawtio-springboot/pom.xml
There is issue with replacing JS code after it was uglified, so release build does not do html5Mode switch for Spring boot and it fails to start properly. See issue https://github.com/hawtio/hawtio/issues/2025
> Fix for #2025, handle html5 deactivation for uglified JS

- hawtio-git/src/main/java/io/hawt/git/GitFacade.java
Remove the System.out.println line. It easily adds up if you use many GitFacade objects.
> Remove System.out line

- circle.yml
- hawtio-git/pom.xml
- hawtio-git/src/main/java/io/hawt/git/GitFacadeSupport.java
- hawtio-sample-springboot-authentication/pom.xml
- hawtio-sample-springboot/pom.xml
- hawtio-system/pom.xml
- hawtio-web/pom.xml
- pom.xml
- Upgrade to Fabric8 gitective 0.9.10
- Upgrade Jgit to latest version
- Switch to JDK 1.8
- Aligned Springboot samples with mainClass configuration property.
Andrea
> Gitective jgit upgrade and switch to jdk 1.8

- hawtio-insight-log/src/main/java/io/hawt/log/LogEvent.java
- hawtio-insight-log/src/main/java/io/hawt/log/LogFilter.java
- hawtio-insight-log/src/main/java/io/hawt/log/LogResults.java
- LogResults, LogFilter and LogEvent marked as serializable
We need the classes in hawtio-insight-log to be marked serializable, as we use a multi-tier application architecture where the "web tier" runs hawtio, but back-end services do not install the http feature, nor do they install jolokia.  In this case, we use federation provided by the legacy jdmk to marshal instance data over rmi (jmx bridging).  Because of this, installing hub/spoke log monitoring doesn't work, and we have to cobble together a delegation model using openmbeans.
Alternately, marking this class as @MXBean would work and not require each tier to have the classes installed.   This change simply marks the beans serializable.
> Mark classes in hawtio-insight-log that are marshaled over jmx as serializable

- hawtio-web/src/main/webapp/app/jvm/js/connect.ts
I am planing on integrating hawtio into a monitoring application we have and wanted the ability to create links that would open up hawtio and automatically connect to specific servers being monitored.
With this change I am able to do so by creating links in this format
/hawtio/index.html#/jvm/connect?name={name}&host={host}&port={port}&path={path}&userName={userName}&password={password}
This is very hacky and I am sure one of you could improve it, I have only started looking at hawtio today and javascript/typescrypt is not something I am too familiar with.
> Addresses ticket #1965

- docs/Articles.md
Fixed spelling of "plugin" in web link. Forgive me for not making a feature branch for this, but this is a drive-by patch on my part. ;)
> Misc : fix typo

- sample-keycloak-integration/README.md
I actually tested this only with tomcat8 adapter, but at least all the links are valid and working now.
> Updated links for keycloak version 1.9.1

- hawtio-osgi-jmx/src/main/java/io/hawt/osgi/jmx/RBACDecorator.java
- hawtio-osgi-jmx/src/test/java/io/hawt/osgi/jmx/RBACDecoratorTest.java
- hawtio-osgi-jmx/src/test/resources/io/hawt/osgi/jmx/RBACDecoratorTest-input.json
The previous fix causes the following `ClassCastException` in the presence of overloaded methods:
```
| ERROR | qtp1069006536-85 | RBACDecorator                    | 204 - io.hawt.hawtio-osgi-jmx - 1.4.0.redhat-630-SNAPSHOT | java.util.LinkedList cannot be cast to java.util.Map
java.lang.ClassCastException: java.util.LinkedList cannot be cast to java.util.Map
at io.hawt.osgi.jmx.RBACDecorator.decorate(RBACDecorator.java:203)
```
> ENTESB-4996 - Fix ClassCastException with overloaded methods in RBACDecorator

- hawtio-karaf/src/main/resources/features.xml
- hawtio-osgi-jmx/pom.xml
- pom.xml
Now for Karaf 4.x:
```
feature:repo-add hawtio <version>
feature:install hawtio
```
installs `hawtio-osgi-jmx` bundle as well. For Karaf 3.x, you need:
```
feature:repo-add hawtio <version>
feature:install hawtio-core
feature:install hawtio-rbac
```
For Karaf 2.x RBAC is not supported since RBAC is introduced to Karaf since 3.0.
> Fix #2146 RBAC with optimised Jolokia call doesn't work on Karaf

- hawtio-web/src/main/webapp/app/activemq/js/activemqPlugin.ts
- hawtio-web/src/main/webapp/app/camel/js/camelPlugin.ts
- hawtio-web/src/main/webapp/app/core/js/workspace.ts
- hawtio-web/src/main/webapp/app/datatable/js/simpleDataTable.ts
- hawtio-web/src/main/webapp/app/jmx/js/attributes.ts
The idea is that each plugin can register onClickHandler on specific table the same way they are declaring columns and then when a click event happend the hawtio-simple-table will propagate it to the plugin. This is used to fix issue #2075  for ActiveMQ and also for Camel plugin for routes/components/endpoints/context
> Pull Request for #2075

- hawtio-system/src/main/java/io/hawt/web/RBACRestrictor.java
- hawtio-system/src/test/java/io/hawt/web/RBACRestrictorTest.java
Write `InstanceNotFoundException` to `INFO` log instead of `ERROR` as sometimes non-existent
MBeans may be invoked intentionally to probe if a component is available.
> ENTESB-5736 - open hawtio tab in new tab/windows produces RBACRestrictor error javax.management.InstanceNotFoundException

- hawtio-system/src/main/java/io/hawt/web/RBACRestrictor.java
- hawtio-system/src/test/java/io/hawt/web/RBACRestrictorTest.java
> ENTESB-5219 - Make RBACRestrictor always use canInvoke(String, String, String[])

- hawtio-system/src/main/java/io/hawt/web/RBACRestrictor.java
https://issues.jboss.org/browse/ENTESB-5775
The order of properties in an object name is critical for Karaf, so we cannot use `ObjectName.getCanonicalName()` to get the object name string for invoking `JMXSecurityMBean`.
See: https://issues.apache.org/jira/browse/KARAF-4600
> ENTESB-5775 - ActiveMQ Browse tab shows no messages for "viewer" role

- hawtio-web/src/main/webapp/app/source/js/source.ts
Fixes issues with blanks in paths when browsing sources with the maven plugin.
java.net.URISyntaxException: Illegal character in path at index 133: http://camel-standalone:8181/jolokia/exec/io.fabric8.insight:type=LogQuery/getSource/se.kth.infosys.camel:camel-spring:0.0.1-SNAPSHOT org.apache.camel:camel-core:2.17.3 com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2 org.slf4j:slf4j-api:1.7.21 com.sun.istack:istack-commons-runtime:2.21 org.glassfish.jaxb:jaxb-core:2.2.11 org.glassfish.jaxb:txw2:2.2.11 com.sun.xml.bind:jaxb-core:2.2.11 org.glassfish.jaxb:jaxb-runtime:2.2.11 com.sun.xml.bind:jaxb-impl:2.2.11 org.apache.camel:camel-spring:2.17.3 commons-logging:commons-logging:1.2 org.apache.activemq:activemq-camel:5.14.0 org.apache.camel:camel-jms:2.16.3 …
> Fix issue with blanks in URIs in log/source browser.

- hawtio-system/src/main/java/io/hawt/system/Authenticator.java
This solves https://github.com/hawtio/hawtio/issues/2195. This still doesn't allow semicolons in  usernames though but it's a start. Perhaps we should put the username and password in different headers?
Cheers!
> Allow semicolons in user passwords when doing basic authentication

- hawtio-web/src/main/webapp/app/core/js/keycloakLogin.ts
- sample-keycloak-integration/README.md
- Test and update instructions for Keycloak with hawtio on EAP 7
- Upgrade instructions to Keycloak 2.2.1, which has fix for nasty javascript bug
- Better error handling on refreshing token or when keycloak server not available
> Keycloak integration with hawtio on EAP

- CHANGES.md
- hawtio-system/src/main/java/io/hawt/web/AuthenticationFilter.java
- hawtio-system/src/main/java/io/hawt/web/LoginServlet.java
Turned out `Subject.doAs(...)` is effectively not available on WildFly / JBoss EAP, so we need to go direct in-vm call when Hawtio detects it's running on WildFly / JBoss EAP.
> Fix #2224 Hawtio cannot run on WildFly when RBAC is enabled

- pom.xml
Updating the version of Apache Commons FileUpload from 1.3.1 to 1.3.2 to remediate a vulnerability as per https://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2014-0050
> Updated commons-fileupload to version 1.3.2 to remove DoS vulnerability

- hawtio-web/src/main/webapp/app/camel/js/camelPlugin.ts
- hawtio-web/src/main/webapp/app/jmx/js/attributes.ts
This fixes https://github.com/hawtio/hawtio/issues/2233
The problem was found inside the Jmx.AttributesController because:
1) `$on("$routeChangeSuccess)" was triggering an `updateTableContents` with a timeout
2) other `$watch`es in the controller were also triggering `updateTableContents`. but these watches were cleaning up the timeout if it was previously setting
3) the fix was to wire the `updateTableContents` on route change success to the cleanup as well
Most of the navigation actions had this problem. While the initial ticket #2233 only mentioned Camel, this fix covers all the flicker problems where JMX attributes module was used
> Fix #2233 Most of the actions on the app were flickering

- hawtio-web/src/main/webapp/app/datatable/js/simpleDataTable.ts
I'm working on a plugin that uses simpleDataTable. It gives javascript errors as row.entity is attempted passed as a function to array.some(...). 
By using similar logic as in reSelectedItems the problem appears to be fixed. Have run both Camel and Quartz plugins without experiencing issues. 
The use of 's.index' appears a bit suspect, but works in my case as the primaryKeyFn only relies on the entity.
> Problem with simpleDataTable.isSelected

- docs/Plugins.md
- website/src/plugins/diagnostics/index.page
Have verified in jetty that pages render OK. 
https://github.com/skarsaune/hawtio/blob/document_diagnostics/docs/Plugins.md
Not able to verify link before it is served as part of hawtio github, but follows pattern from other plugins.
> Document diagnostics

- hawtio-web/src/main/webapp/app/quartz/doc/help.md
- hawtio-web/src/main/webapp/app/quartz/html/triggers.html
- hawtio-web/src/main/webapp/app/quartz/js/quartz.ts
Allows the developer to invoke a Quartz trigger directly from the GUI in order to test the underlying application.
Usage: 
Select a trigger in the Quartz/triggers tab.
Hit the play button to the trigger toolbar.
A dialog with parameters will appear:
Hit "Trigger now" and a message with the outcome will appear. 
Inn addition the last previous fire timestamp in the table will be updated:
Manual trigger is possible even if the trigger is paused.
This new feature is unfortunately affected by the same bug as the edit dialog, described in issue #2348.
> Quartz manual trigger dialog

- hawtio-web/src/main/webapp/app/diagnostics/js/diagnosticHelpers.ts
- hawtio-web/src/main/webapp/app/diagnostics/js/diagnosticsPlugin.ts
Tested on zulu JDK where Heap tab is shown and selected , and flight recorder tab is hidden. 
All three tabs still appear in Oracle JDK8.
Since the tab breadcrumbs are built in diagnosticsHelpers.ts one alternative would be to only add the breadcrumbs that are valid and pick the URL of the first breadcrumb if any, instead of adding all with isValid filters.
> #2350 detect what parts of the diagnostic tools are in fact available

- hawtio-web/src/main/webapp/app/jvm/html/discover.html
- hawtio-web/src/main/webapp/app/jvm/js/discover.ts
Idea: provide more details about the Java application of the discovered agents. This can be useful if there are a lot of different Java processes running and one wants an idea of which is which before actually connecting. It will only be attempted for connections without authentication (did not find a good way to deal with authentication). A downside is that there may be up to a couple of extra requests for each discovered agent. However the timeout for the discovery process is so long that the user will probably not notice much difference.
On a best effort basis, the following is attempted for each generic detected vm: 
- Main class / jar file and arguments
- Start time of the application (you often have an idea about when a version was deployed)
> Detect more details about the JVM of the discovered agents

- .gitignore
- hawtio-web/src/main/webapp/app/diagnostics/html/jfr.html
- hawtio-web/src/main/webapp/app/diagnostics/js/jfr.ts
Background: The DiagnosticCommand operations have both differing input requirements and response between Java 8 and Java 9.
Goal: Adjust the implementation so that it supports both versions.
Implementation details: 
- Drop compress option as it is no longer supported
- Base operations for existing recording on recording name rather than number
- Allow starting new recordings even if there are stopped ones (are not removed by stop in Java 9)
- Support maxsize limit of recordings
Tested successfully in Java versions 9+181, 1.8.102 & 1.8.152.
> JFR support for Java 9

- hawtio-springboot/pom.xml
- hawtio-springboot/src/main/java/io/hawt/springboot/HawtioConfiguration.java
- hawtio-springboot/src/test/java/io/hawt/springboot/HawtioConfigurationTest.java
- pom.xml
Sometimes it might not be desirable to start Hawtio automatically as soon as it is included on the class path. This enhancement allows to disable Hawtio via configuration property "hawtio.enabled" which defaults to "true", but can be overridden if necessary.
> Spring: add ability to disable Hawtio via properties

- hawtio-web/src/main/webapp/app/activemq/js/activemqPlugin.ts
- hawtio-web/src/main/webapp/app/camel/js/camelHelpers.ts
- hawtio-web/src/main/webapp/app/camel/js/endpointChooser.ts
- hawtio-web/src/main/webapp/app/camel/js/propertiesComponent.ts
- hawtio-web/src/main/webapp/app/camel/js/propertiesDataFormat.ts
- hawtio-web/src/main/webapp/app/camel/js/propertiesEndpoint.ts
This commit updates all icon image references to use relative paths. This makes sure that icon images can be properly requested even when running hawtio with a custom context path.
This issue was found when running Spring Boot and hawtio with a custom context path. All images in the "Route Diagram" tab were not rendered properly, because they were requested using absolute paths starting with `/img/`.
> Use relative paths for icon images

- hawtio-sample-springboot/pom.xml
The Spring Boot sample should use the same Camel version as configured in the parent.
> Use Camel version property from parent

- examples/springboot-authentication/pom.xml
@tadayosi I assume this change is fine? The springboot-authentication quickstart seems to work fine with Undertow, and it brings it into line with the normal springboot quickstart.
> chore: Use spring-boot-starter-undertow instead of jetty

- platforms/springboot/src/integration-test/java/io/hawt/springboot/HawtioSpringBootExposedEndpointIT.java
- platforms/springboot/src/main/java/io/hawt/springboot/ExposedEndpoint.java
Currently when setting `management.endpoints.web.exposure.include=*` in application.properties to expose all available Spring Actuators, `@ConditionalOnExposedEndpoint(name = "jolokia")` evaluates to `false` which prevents initialization of `HawtioManagementConfiguration#hawtioUrlMapping(..)` and `HawtioManagementConfiguration#authenticationFilter(..)`.
> Fixes hawtio not configured correctly when all actuators are exposed

- hawtio-system/src/main/java/io/hawt/jmx/RBACRegistry.java
Address and Queue MBeans have different names in Artemis compared to ActiveMQ 5. 
This PR implements the same MBean caching mechanims for Artemis. Without caching HawtIO UI fails to load for Artemis servers with some hundred or thousand queues.
> Support caching of ActiveMQ Artemis Address/Queue MBeanInfos

- hawtio-log-osgi/pom.xml
Resolves dependencies on OSGi R7 containers like Karaf 4.3.0
> #2618 Support for OSGi R7 Pax Logging

- platforms/wildfly/pom.xml
Log4j shows up in QWASP Dependency Check report for CVE-2019-17571.
As Wildfly provides an implementation of log4j 1.x which addresses this problem the jar is not needed in the WAR.
> exclude-log4j-from-hawtio-wildfly-war

- hawtio-base/src/main/webapp/WEB-INF/web.xml
- hawtio-system/src/main/java/io/hawt/web/filters/FlightRecordingDownloadFacade.java
- hawtio-war/src/main/webapp/WEB-INF/web.xml
- platforms/osgi-war/src/main/webapp/WEB-INF/web.xml
https://github.com/hawtio/hawtio-integration/pull/109 requires on this to work. More functional details are in that PR.
As it is a servlet filter it works both for hawtio JVM and others via proxy
> Create synthetic FlightRecorder operation to be downloaded as a stream

- pom.xml
from 2.14 to 2.15 to get the Log4shell CVE fix.
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2314720
> Update pom.xml to upgrade log4j2 version

- pom.xml
because of:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228
this addresses issue #2712
> bump log4j2 again

- pom.xml
Bump Log4j to 2.17.1 to fix [CVE-2021-44832](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832)
> Bump Log4j to 2.17.1

- hawtio-system/src/main/java/io/hawt/system/Authenticator.java
I tried to secure hawt.io console with keycloak based on hawt.io documentation but also based on the example of activemq artemis. Unfortunately i was not able to make it working and therefore started debugging. I found the problem in class io.hawt.system.Authenticator which does only support Basic Http Header Authorization but not the Bearer token. I have extended the class to make this working.
It seems that there is also a corresponding problem in the javascript code because even if i am redirected to keycloak authentication page the token is never passed with the request. FOr me so far this is no problem because i do authentication in a proxy service which will then pass the token properly the hawtio server.
> add support for Bearer Token based Authentication

- hawtio-console-assembly/app/package.json
- hawtio-console-assembly/app/yarn.lock
Since we have added a new feature of enabling info tabs and removing unnecessary endpoints we have updated the hawtio-integration verison
1. https://github.com/hawtio/hawtio-integration/pull/135
2. https://github.com/hawtio/hawtio-integration/pull/132
> chore update hawtio-integration verion to 4.16.7

- hawtio-system/src/main/java/io/hawt/web/auth/Redirector.java
- hawtio-system/src/test/java/io/hawt/web/auth/RedirectorTest.java
https://issues.redhat.com/browse/ENTESB-17301
> fix(system): ENTESB-17301 redirect with scheme adds default port 80 or 443 explicitly

- .github/workflows/stale.yml
Added a github action stale which adds tags to the PR's and issues with over a year of inactivity. They are automatically closed after 14 days of adding the stale tag. The entire repository gets checked at 12:00 AM GMT. Resolves the issue https://github.com/hawtio/hawtio/issues/2726
> chore: added github action stale

- hawtio-console-assembly/app/package.json
- hawtio-console-assembly/app/yarn.lock
In response to the community user's issue : https://github.com/hawtio/hawtio-integration/issues/131 ;we have updated the upstream camel version to "3.14.2"  in the PR: https://github.com/hawtio/hawtio-integration/pull/138.
This closes the issue : https://github.com/hawtio/hawtio/issues/2736
> chore: updated hawtio-integration version to 5.0.0

- hawtio-system/src/main/java/io/hawt/web/filters/FlightRecordingDownloadFacade.java
When `super.getPathInfo()` be null, this Request Wrapper will throw an NPE.
> Fix NPE in FlightRecordingDownloadFacade

- hawtio-console-assembly/app/package.json
- hawtio-console-assembly/app/yarn.lock
This new version enables the option to view the entire thread Dump and closes the issue https://github.com/hawtio/hawtio-integration/issues/142.
> chore: updated hawtio-integration version to 5.0.2

- hawtio-system/src/main/java/io/hawt/web/filters/ContentSecurityPolicyFilter.java
- hawtio-system/src/main/java/io/hawt/web/filters/HttpHeaderFilter.java
- hawtio-system/src/main/java/io/hawt/web/filters/XFrameOptionsFilter.java
- hawtio-system/src/test/java/io/hawt/web/filters/ContentSecurityPolicyFilterTest.java
Now by default Hawtio sets the following HTTP headers:
X-Frame-Options: DENY
Content-Security-Policy: frame-ancestors 'none'
Optionally, you can restore the original behaviour by setting the following system property:
hawtio.http.allowXFrameSameOrigin=true
> fix(system): ENTESB-19673 switch X-Frame-Options default to DENY

- hawtio-base/src/main/webapp/WEB-INF/web.xml
- hawtio-system/src/main/java/io/hawt/web/filters/ReferrerPolicyFilter.java
- hawtio-war/src/main/webapp/WEB-INF/web.xml
- platforms/osgi-war/src/main/webapp/WEB-INF/web.xml
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioManagementConfiguration.java
- platforms/wildfly/src/main/webapp/WEB-INF/web.xml
Now by default Hawtio sets the following HTTP header:
Referrer-Policy: no-referrer
Optionally, you can customise the header by setting the following system property:
hawtio.http.referrerPolicy=...
> fix(system): ENTESB-19674 set Referrer-Policy to no-referrer by default

- hawtio-system/src/main/java/io/hawt/web/filters/CORSFilter.java
Now by default Hawtio stops sending the following HTTP header:
Access-Control-Allow-Origin: ...
Optionally, you can restore the original behaviour by setting the following system property:
hawtio.http.enableCORS=true
Also when enabled, you can customise the header by setting the following system property:
hawtio.http.accessControlAllowOrigin=https://example.com
> fix(system): ENTESB-19675 disable CORSFilter by default

- pom.xml
The fix for Mac M1 users
The project tries to install node v14.17.3
`[INFO] Downloading https://nodejs.org/dist/v14.17.3/node-v14.17.3-darwin-arm64.tar.gz to /Users/tsedmik/.m2/repository/com/github/eirslett/node/14.17.3/node-14.17.3-darwin-arm64.tar.gz`
However, darwin-arm64 is supported since Node 19+
https://nodejs.org/dist/v14.17.3/
`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) on project hawtio-console-assembly: Could not download Node.js: Got error code 404 from the server. -> [Help 1]`
I updated the `frontend-maven-plugin-version` to 1.12.1
> [Fix] darwin-arm64 is supported since node 19

- .github/workflows/e2e_test.yml
A new workflow to run E2E tests per pull req and commits as asked in the https://github.com/hawtio/hawtio/issues/2790
Right now it will trigger E2E tests only on Spring Boot runtime as there are no tests for Quarkus yet.
> [E2E] GitHub Workflow to run E2E per pull req and commit

- pom.xml
- tests/pom.xml
Before E2E tests were triggered in the Test workflow and caused test execution duplication in both workflows - Test and E2E Tests.
Now E2E tests are triggered only in E2E test workflow.
Also, the timeout in maven surefire was increased as it caused issued before.
> [Workflow] Exclude E2E tests from Test workflow and increase timeout

- tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/HawtioPage.java
- tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/quartz/QuartzPage.java
The E2E tests became [flaky](https://github.com/hawtio/hawtio/issues/2815) and most failures were related to one method. By default, the tests are running in a background (headless mode) and most likely there were situations (connectivity issues like delays) when Selenide thought that some menu tabs were hidden under More tab (drop-down menu) and it was waiting for it. It was causing test failures and a job rerun was required. 
With this method deletion the situation should be stabilised.
> [E2E Tests] Stabilize open menu tabs method

- tests/springboot/.gitignore
- tests/springboot/src/test/resources/features/plugin/plugin.feature
- tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/plugin/PluginPage.java
- tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/plugin/PluginStepDefs.java
In this MR:
- Basic test checking ability to access the Sample plugin (whether it got installed and got accessed in UI)
- Basic test checking the content view of the Sample plugin (title and paragraph)
- Also, I added a `.gitignore` file into `tests/springboot/` to ignore `/build` directory
> [E2E Tests] Add basic test for Sample Plugin

- examples/quarkus/pom.xml
@tadayosi this is typically how the build order is forced in the camel-quarkus and quarkus projects.
> fix(examples): Add pseudo POM dependency for hawtio-quarkus-deployment to enforce the correct reactor build order

- tests/pom.xml
- tests/quarkus/src/test/resources/features/camel/contexts/camel_contexts.feature
- tests/springboot/src/test/resources/features/camel/contexts/camel_contexts.feature
- tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/Panel.java
- tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/CamelTree.java
- tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/menu/Menu.java
In this PR:
- Test frameworks version updates
- Log out action fix
- Camel tree id-s stabilization
- Added one check as at some point Hawtio is slower than Selenide and sometimes the content is not loaded properly
The github checks will fail (usually, 3-4 failing tests scenarios per runtime) because of https://github.com/hawtio/hawtio-next/issues/318
> [E2E Tests] Camel tree id-s tests and log out stabilization, version updates.

- platforms/springboot/src/main/java/io/hawt/springboot/HawtioEndpoint.java
- platforms/springboot/src/test/java/io/hawt/springboot/HawtioEndpointTest.java
This PR fixes the issue https://github.com/hawtio/hawtio/issues/2855 and applies same behavior as quarkus app (redirect in case of missing / in case of `actuator/hawtio`). Though I am not sure if there is another (better) way to achieve the same result.
> Add redirect to hawtio/

- examples/springboot-authentication-jar/pom.xml
- examples/springboot-authentication-jar/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
- examples/springboot-authentication/pom.xml
- examples/springboot-authentication/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
- hawtio-embedded/pom.xml
- hawtio-embedded/src/main/java/io/hawt/embedded/Main.java
- pom.xml
- tests/springboot/pom.xml
- tests/springboot/src/main/java/io/hawt/tests/spring/boot/PropertyFileLoginModule.java
- tooling/hawtio-maven-plugin/pom.xml
In addition to the cherry-pick from 3.x branch, I had to add the following:
- Explicitly set `maven-plugin-plugin` version because it was clashing with jetty 10
- Add `javax.servlet-api` to hawtio-embedded, given that is not provided by jetty 10 (I wonder why though)
> Jetty 10 Upgrade for 2.x

- console/craco.config.js
- console/package.json
- console/yarn.lock
- examples/sample-plugin/craco.config.js
- examples/sample-plugin/package.json
- examples/sample-plugin/yarn.lock
From testing on my machine this change speeds up prod builds from around 2 minutes to around 30 seconds.
I noticed @tadayosi encountered the same issue as me https://github.com/module-federation/universe/issues/827, so I used the suggested workaround
> Use esbuild plugin to speedup JS builds

- .github/workflows/image.yml
- tests/hawtio-test-suite/pom.xml
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/hooks/SkipTestsHook.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/ConnectPage.java
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/panel/about/about_modal_window.feature
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/plugin/plugin.feature
Builds test images on push and pushes them to Quay to be reused in hawtio-next.
Add tags to skip tests that require configuration that is not done in hawtio-next tests.
Related to https://github.com/hawtio/hawtio-next/pull/457
> ci: Publish e2e docker images into quay.io

- pom.xml
jetty 10 need javax.servlet 4.0.1, and the karaf version we had was too old for javax.servlet 4.0.1.
> Bump javax servlet and karaf version

- deploy/hawtio-base/pom.xml
- deploy/hawtio-base/src/main/webapp/WEB-INF/web.xml
- deploy/hawtio-embedded/pom.xml
- deploy/hawtio-embedded/src/main/java/io/hawt/embedded/Main.java
- hawtio-war/src/main/webapp/WEB-INF/web.xml
- platforms/springboot/pom.xml
- platforms/springboot/src/integration-test/java/io/hawt/springboot/HawtioSpringBootCustomManagementPortIT.java
- platforms/springboot/src/integration-test/java/io/hawt/springboot/HawtioSpringBootTestSupport.java
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioEndpoint.java
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioEndpointAutoConfiguration.java
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioManagementConfiguration.java
- platforms/springboot/src/main/java/io/hawt/springboot/JolokiaEndpoint.java
- platforms/springboot/src/main/java/io/hawt/springboot/JolokiaEndpointAutoConfiguration.java
- platforms/springboot/src/main/java/io/hawt/springboot/JolokiaProperties.java
- platforms/springboot/src/main/java/io/hawt/springboot/SpringHawtioContextListener.java
- platforms/springboot/src/main/resources/META-INF/spring.factories
- platforms/springboot/src/main/resources/META-INF/spring/org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration.imports
- platforms/springboot/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- platforms/springboot/src/test/java/io/hawt/springboot/HawtioEndpointTest.java
- platforms/springboot/src/test/java/io/hawt/springboot/SpringHawtioContextListenerTest.java
- pom.xml
I've upgraded the version of sb to sb3. I'm still facing the problems with resolving index.html and other things.
1.  It looks like links in static files aren't properly regenerated (probably responsibility of  `ResourceUrlEncodingFilter`) when management.server.port is configured to the different port as the server.port. When management.server.port isn't configured hawtio application is properly resolved.
2. application is resolved only when  directly  index.html is requested. When `actuator/hawtio/` is requested then I'm getting 404. This probably can be fixed by manual redirect to index.html in HawtioEndpoint but I don't feel that's the best solution. Probably the ResourceHandlers has to be tweaked.
> Upgrade to jetty12.0.0beta3 and spring-boot 3 

- examples/springboot-security/src/main/java/io/hawt/example/spring/boot/SecurityConfig.java
This PR reflects changes of spring-security 6. Mainly moving out of `WebSecurityConfigurerAdapter` and change in csrf token behaviour that mitigates BREACH vulnerability and by default might not work with JS applications
related to #2819
> refactor(examples): spring-security example to work with spring-boot 3 and spring-security 6

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelChart.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/CamelChartStepDefs.java
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/contexts/camel_specific_context.feature
New test scenarios for Camel Context covering:
- Camel Chart
- View Chart
- Edit Chart
- Camel Operatios
- Execute the operation returning a result of `boolean` type
- Execute the operation returning a result of `int` type
> [E2E Tests] New Camel Contexts Operations and Chart test scenarios

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/CamelTree.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/endpoints/CamelBrowse.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/endpoints/CamelSend.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/endpoints/CamelEndpointsStepDefs.java
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/endpoints/camel_specific_endpoint.feature
In this PR I added:
- Camel Endpoint messaging E2E tests (send, browse, forward, view)
- Fix a test method when expanding an item in the Camel tree (if already expanded - do not click again)
> [E2E Tests] Camel Endpoint messaging tests

- examples/springboot-log4j2/pom.xml
- examples/springboot/pom.xml
- pom.xml
- tests/pom.xml
Jetty 12 is finally released and so is camel 4.
> chore: update camel version in examples to 4.0.0  jetty to 12.0.1

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/panel/about/AboutModalWindowStepDefs.java
Hi @tadayosi 
It seems the previous fix wasn't enough, I assume everytime the id if the title in the Aboud dialog has different digit suffix. So I have changed the selector. Hopefully, it will resolve the issue
Thanks
> [E2E Tests] Fix About dialog tests

- .github/workflows/e2e_test.yml
- deploy/hawtio-base/pom.xml
- deploy/hawtio-default/pom.xml
- examples/springboot/src/main/java/io/hawt/example/spring/boot/SampleSpringBootService.java
- examples/war-plugin/pom.xml
- hawtio-system/pom.xml
- hawtio-system/src/main/java/io/hawt/system/RBACRestrictor.java
- hawtio-system/src/main/java/io/hawt/web/ServletHelpers.java
- hawtio-system/src/main/java/io/hawt/web/auth/LoginServlet.java
- hawtio-system/src/main/java/io/hawt/web/plugin/PluginServlet.java
- hawtio-system/src/main/java/io/hawt/web/servlets/JolokiaConfiguredAgentServlet.java
- hawtio-system/src/test/java/io/hawt/system/RBACRestrictorTest.java
- hawtio-system/src/test/java/io/hawt/web/ServletHelpersTest.java
- platforms/springboot/pom.xml
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioEndpoint.java
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioManagementConfiguration.java
- platforms/springboot/src/main/java/io/hawt/springboot/JolokiaEndpoint.java
- platforms/springboot/src/main/java/io/hawt/springboot/JolokiaEndpointAutoConfiguration.java
- platforms/springboot/src/main/java/io/hawt/springboot/TrailingSlashFilter.java
- plugins/hawtio-local-jvm-mbean/pom.xml
- pom.xml
- tests/quarkus/src/main/java/io/hawt/tests/quarkus/SampleCamelRoute.java
- tests/springboot/src/main/java/io/hawt/tests/spring/boot/PropertyFileLoginModule.java
- tests/springboot/src/main/java/io/hawt/tests/spring/boot/SampleCamelRouter.java
- tests/springboot/src/main/java/io/hawt/tests/spring/boot/SpringBootService.java
Applied the official Jolokia 2.0.0-SNAPSHOT artifacts to 4.x branch. Right now, it uses jitpack for CI to resolve the snapshot jar dependencies. Once we have a new Jolokia 2.0.0 milestone release, we can remove the jitpack usage.
cc @mmelko 
should fix #2866 #2867 #2868
> fix(system): apply new Jolokia 2.0.0 (snapshot version)

- .github/workflows/e2e_test.yml
- tests/quarkus/src/main/docker/Dockerfile.jvm
- tests/springboot/Dockerfile
> ci(e2e): add Java 21 to E2E tests

- .github/workflows/audit.yml
- console/pom.xml
- examples/sample-plugin/pom.xml
This adds a new workflow 'Audit', which runs weekly on every Sunday to periodically audit the npm dependencies.
It also inserts audit steps to building of console and sample-plugin, so that every pull request is also audited against the potentially added dependencies.
> ci: HAWNG-281 apply yarn npm audit to workflow

- console/pom.xml
- examples/sample-plugin/pom.xml
- pom.xml
This is needed as with older Node versions connection through IPv6 was unstable. This should fix the issue. 
Btw @tadayosi what do you think about moving these properties to the parent pom so we can upgrade the versions in just one place?
> build: Bump Node versions update for maven frontend plugin

- deploy/hawtio-default/src/main/webapp/WEB-INF/web.xml
- examples/quarkus-keycloak/src/main/resources/application.properties
- examples/quarkus/src/main/resources/application.properties
- hawtio-system/src/main/java/io/hawt/HawtioContextListener.java
- hawtio-system/src/main/java/io/hawt/system/Authenticator.java
- hawtio-system/src/main/java/io/hawt/system/ConfigManager.java
- hawtio-system/src/main/java/io/hawt/web/auth/AuthSessionHelpers.java
- hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationConfiguration.java
- hawtio-system/src/main/java/io/hawt/web/auth/SessionExpiryFilter.java
- hawtio-system/src/main/java/io/hawt/web/auth/UserServlet.java
- hawtio-system/src/main/java/io/hawt/web/auth/keycloak/KeycloakServlet.java
- hawtio-system/src/main/java/io/hawt/web/proxy/ProxyServlet.java
- hawtio-system/src/main/java/io/hawt/web/tomcat/TomcatAuthenticationContainerDiscovery.java
- hawtio-system/src/test/java/io/hawt/system/ConfigManagerTest.java
- hawtio-system/src/test/java/io/hawt/web/auth/LoginRedirectFilterTest.java
- hawtio-war/src/main/webapp/WEB-INF/web.xml
- platforms/quarkus/deployment/src/main/java/io/hawt/quarkus/deployment/HawtioProcessor.java
- platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusAuthenticationEnabledTest.java
- platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/HawtioConfig.java
- platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/auth/HawtioQuarkusAuthenticator.java
- platforms/springboot/src/test/java/io/hawt/springboot/SpringHawtioContextListenerTest.java
- tests/quarkus/src/main/resources/application.properties
> fix(system): make system properties the only method to configure hawtio

- hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationConfiguration.java
- hawtio-system/src/main/java/io/hawt/web/auth/SessionExpiryFilter.java
- hawtio-system/src/main/java/io/hawt/web/auth/UserServlet.java
- hawtio-system/src/main/java/io/hawt/web/auth/keycloak/KeycloakUserServlet.java
It also refactors around AuthenticationConfiguration and filter and servlet that use it.
> feat(system): introduce hawtio.ae as shorthand for hawtio.authenticationEnabled

- hawtio-jbang/dist/HawtioJBang.java
- hawtio-jbang/src/main/jbang/main/HawtioJBang.java
This should enable users to run a Hawtio version provided on MRRC as follows:
```console
jbang -Dhawtio.jbang.version=4.0.0.redhat-00029 hawtio@hawtio/hawtio
```
@Croway Please review this to check if I'm doing it correctly.
> feat(jbang): support red hat maven repositories for jbang

- hawtio-system/src/main/java/io/hawt/web/proxy/ProxyServlet.java
I rewrote how URL is crafted. This should prevent open redirect vulnerability.  This code is reachable only when status from the proxy is between 300 and 303 (when redirect is necessary) which is not  often AFAIK.
> fix(ProxyServlet): Refactor how url being created when 300-303 status is received

- hawtio-system/src/main/java/io/hawt/web/filters/ContentSecurityPolicyFilter.java
- hawtio-system/src/test/java/io/hawt/web/filters/ContentSecurityPolicyFilterTest.java
Looks like we don't need this for the nawtio-next and we are not using inline scrips. I also verified that CSP header is modified and hawtio is working with this settings.
> fix(HAWNG-5): Remove unsafe-eval and unsafe-inline from the CSP header

- hawtio-system/pom.xml
- hawtio-system/src/main/java/io/hawt/jmx/RBACRegistry.java
- hawtio-system/src/main/java/io/hawt/system/RBACMBeanInvoker.java
- hawtio-system/src/main/java/io/hawt/web/filters/BaseTagHrefFilter.java
- platforms/springboot/src/main/java/io/hawt/springboot/ExposedEndpoint.java
- platforms/springboot/src/main/java/io/hawt/springboot/HawtioManagementConfiguration.java
- pom.xml
- tests/hawtio-test-suite/pom.xml
- tests/pom.xml
* For better caching performance
* Removing dependency to guava
* In preparation for authentication throttling implementation
> refactor(system): switch from guava cache to caffeine

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/online/DiscoverTab.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/openshift/HawtioOnlineLoginPage.java
- tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/ClusterDiscoveryTest.java
- tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/utils/SelenideTestWatcher.java
- tests/hawtio-test-suite/src/test/java/io/hawt/tests/utils/rp/Attachments.java
- tests/hawtio-test-suite/src/test/java/io/hawt/tests/utils/rp/RPTestExecutionListener.java
- tests/hawtio-test-suite/src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
The RP client can attach files to specific test cases; this code screenshot is included with any failing test. 
+ fixed some flakiness when it came to testing on strained cluster & added logic to wait for the long initial load of Hawtio Online
> Add screenshots to Report Portal + fix flaky Openshift tests

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/ConnectPage.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/LoginPage.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/WebDriver.java
Fixes issue with Chrome password popup, missing crypto on localhost & the connect button click being ignored by the browser
> Fix e2e errors

- hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationFilter.java
Fix the issue that CORS preflight requests are not accepted with Artemis brokers.
> fix(system): AuthenticationFilter should ignore CORS preflight requests

- hawtio-system/src/main/java/io/hawt/web/filters/ContentSecurityPolicyFilter.java
- hawtio-system/src/test/java/io/hawt/web/filters/ContentSecurityPolicyFilterTest.java
> fix(#3333): enable 'unsafe-inline' for stype sources in CSP header to properly load styles for the monaco-editor

- platforms/quarkus/deployment/pom.xml
- platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/auth/HawtioQuarkusAuthenticator.java
> fix(quarkus): quarkus when auth disabled should not fail to build without security extension

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelChart.java
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/contexts/camel_specific_context.feature
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/routes/camel_specific_route.feature
According to UX changes in Charts, there is a test refactoring.
New UX changes also brought a few difficulties as chart's title is not as one complete text, but several texts, so a more complex solution with Xpath has been applied where it's needed to select the desired title using text's index.
> [E2E Tests] Refactor Chart tests according to UX changes

- .github/workflows/image.yml
The fabric8 maven plugin fails when the same argument is specified in 2 different places (although in this case it had the same value). The values are now set automatically in the pom.xml from the current java version.
> fix(ci): fix build image job

- platforms/springboot/src/main/java/io/hawt/springboot/HawtioEndpoint.java
- platforms/springboot/src/main/java/io/hawt/springboot/TrailingSlashFilter.java
When opening new connection tab from Hawtio on Spring Boot, we're getting redirected without con parameter. This commit fixes this problem.
Fixes #3317
> fix(connect): Handle redirect with "con" parameter for proxy requests

- pom.xml
* The CVE requires the upgrade of spring products to 6.1.6+. To achieve this upgrade both the spring version and the springboot version in the pom configuration.
* See CVE described by https://spring.io/security/cve-2024-22262
> fix: Upgrades springboot to 3.2.5

- tests/hawtio-test-suite/pom.xml
This will rerun failed tests up to 3 times, the tests that pass on the retry are marked as flakes. For example: sometimes it happens that Hawtio doesn't load in time (there's about 30 second wait time), while we could always increase the wait time, it makes more sense to rerun the test again with the sensible time.
> e2e: rerun failed tests

- tests/README.md
- tests/hawtio-test-suite/pom.xml
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/config/TestConfiguration.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/openshift/HawtioOnlineUtils.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/openshift/OpenshiftClient.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/openshift/PodEntry.java
- tests/hawtio-test-suite/src/test/java/io/hawt/tests/utils/HawtioOnlineTestUtils.java
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/panel/help/help.feature
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/openshift/camelk-e2e-integration.groovy
Allows using a Camel-K integration for E2E tests. Normally the latest Red Hat version from OperatorHub is used, but it can also be configured to use a different catalog by a property. 
Updated the readme to mention Camel K as well as changing / removing some outdated info. IMO it's not worth it to state the versions in the README as it's not always up to date with the pom
> e2e: add camel-k integration to Hawtio Online tests

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/ConnectPage.java
The changes introduced in https://github.com/hawtio/hawtio-next/pull/930 cause E2E tests failures.
It happened due to default HTPPS scheme when a new connection is created.
The fix for E2E tests is to switch from default HTTPS to HTTP scheme when creating a new connection.
> [E2E Tests] Disable default HTTPS scheme when creating a new connection

- platforms/quarkus/deployment/src/main/java/io/hawt/quarkus/deployment/HawtioProcessor.java
Fix #3495
@grgrzybek @jamesnetherton Wow, the fix turned out to be so simple!  Thanks James.
Now with the fix, `mvn clean install -Dquarkus.package.type=uber-jar -pl examples/quarkus` results in the following `META-INF/jolokia/services-default` in the uber-jar:
```java
org.jolokia.service.serializer.JolokiaSerializer,10
org.jolokia.service.jmx.LocalRequestHandler,1000
org.jolokia.service.discovery.JolokiaDiscovery
org.jolokia.service.discovery.DiscoveryMulticastResponder
org.jolokia.service.history.HistoryMBeanRequestInterceptor
org.jolokia.service.jsr160.Jsr160RequestHandler
org.jolokia.service.notif.pull.PullNotificationBackend
org.jolokia.service.notif.sse.SseNotificationBackend
```
> fix(quarkus): Jolokia not working with Quarkus when building uber-jar

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/routes/CamelProperties.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/routes/CamelRoutesStepDefs.java
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/routes/camel_specific_route.feature
Add a new test scenario checking Camel Routes Properties tab.
In this specific scenario the quartz simple route properties are checked.
> [E2E Tests] Add tests checking Camel Route Properties tab

- examples/quarkus/pom.xml
Minor UX improvement.
`camel-quarkus-management` depends on `camel-quarkus-xml-jaxb`, which is enough for route dumping etc. In future CQ releases, the management extension will use the lightweight xml-io component, so it's probably best to clean up the example ahead of this.
> Remove redundant camel-quarkus-jaxb from Quarkus example project

- hawtio-system/src/main/java/io/hawt/system/Authenticator.java
- hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationConfiguration.java
- hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationFilter.java
- hawtio-system/src/main/java/io/hawt/web/auth/oidc/OidcLoginModule.java
- hawtio-system/src/main/java/io/hawt/web/proxy/ProxyDetails.java
- platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/filters/HawtioQuarkusAuthenticationFilter.java
This is required when `Authorization` header carries a Bearer token for OIDC/Keycloak authentication, while we also have to pass credentials for remote Jolokia agent (accessible via "Connect" tab)
> feat(system): Support X-Jolokia-Authorization header (#3404)

- pom.xml
With this, upstream E2E will no longer pass green until RHBAC for SB 4.8.0 version is released.
> fix: HAWNG-851 Update RHBAC for Spring Boot version to 4.8.0

- platforms/quarkus/deployment/pom.xml
- platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusAuthenticationDisabledTest.java
- platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusAuthenticationEnabledTest.java
- platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusPluginConfigurationTest.java
- platforms/quarkus/runtime/pom.xml
- pom.xml
Added -AlegacyConfigRoot=true to keep legacy @ConfigRoot for Quarkus because the new @ConfigMapping has unresolvable issues #3704 at this moment.
> chore(deps): upgrade to Quarkus 3.15.2 LTS

- .github/workflows/e2e_test.yml
- examples/keycloak-integration/hawtio-demo-realm.json
- tests/hawtio-test-suite/pom.xml
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/config/TestConfiguration.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/hooks/DeployAppHook.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/hooks/SkipTestsHook.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/LoginLogout.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/WebDriver.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/deployment/DockerDeployment.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/deployment/KeycloakDeployment.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/deployment/MavenDeployment.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/utils/TestUtils.java
- tests/hawtio-test-suite/src/main/resources/keycloak-demo-realm.json
- tests/hawtio-test-suite/src/main/resources/logback-test.xml
- tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/security/throttling.feature
- tests/quarkus/.dockerignore
- tests/quarkus/pom.xml
- tests/quarkus/src/main/docker/Dockerfile.jvm
- tests/quarkus/src/main/resources/application-keycloak.properties
- tests/quarkus/src/main/resources/application.properties
- tests/quarkus/src/main/resources/keycloak-hawtio.json
- tests/quarkus/start-keycloak.sh
- tests/springboot/pom.xml
- tests/springboot/src/main/java/io/hawt/tests/spring/boot/ApplicationNoSecurity.java
- tests/springboot/src/main/resources/application-keycloak.properties
- tests/springboot/src/main/resources/application.properties
- tests/springboot/src/main/resources/hawtio-static/keycloak-hawtio.json
See passing runs: https://github.com/mmuzikar/hawtio/actions/runs/13110882131
Runs the standard testsuite using admin account on keycloak.
> e2e: add automated testing support for keycloak on quarkus

- platforms/jetty-security/pom.xml
With this profile, `hawtio-jaas.mod` will be attached to the build normally, but there'll be an option to disable this attachment with `-P-jetty-module`.
> chore(build): Attach Jetty hawtio-jaas.mod in dedicated profile

- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/endpoints/CamelSend.java
- tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/routes/CamelSource.java
In this PR:
- Fixed Camel Endpoints messaging tests (Send, Browse, etc.);
- Fixed Camel Routes Source tests to view a code;
The failures were causing because of replacing textarea by span elements wrapped inside div elements.
> [E2E] Fix Camel messaging tests and Camel Source view code test

- console-minimal/package.json
- console-minimal/yarn.lock
- console/package.json
- console/yarn.lock
- examples/sample-plugin/package.json
- examples/sample-plugin/yarn.lock
Support for Camel model versions is now 4.8.x and 4.10.x LTS. Camel model 4.4.x is dropped (4.8.x model will be used).
> feat: update @hawtio/react to 1.9.0

- hawtio-system/src/main/java/io/hawt/web/filters/CacheHeadersFilter.java
Pragma header is deprecated - Cache-Control is enough.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Pragma
> Remove deprecated Pragma header
