hawtio-jboss/compatibility.md

Fix for hawtio https://github.com/hawtio/hawtio/issues/1834

Added JBoss EAP 6 compatability matrix

---

hawtio-system/src/main/java/io/hawt/web/UserServlet.java
hawtio-system/src/main/java/io/hawt/web/keycloak/KeycloakServlet.java
hawtio-web/src/main/webapp/app/core/js/app.ts
hawtio-web/src/main/webapp/app/core/js/keycloakLogin.ts
hawtio-web/src/main/webapp/index.html
sample-keycloak-integration/README.md
sample-keycloak-integration/demorealm.json

- Support for links to Keycloak admin console and account management (if KC integration enabled)
- Fix the wildfly issue when AuthenticationFilter and UserServlet could return different values for 'authenticationEnabled'

KC integration improvements

---

docs/Configuration.md
hawtio-system/src/main/java/io/hawt/web/tomcat/TomcatAuthenticationContainerDiscovery.java
hawtio-system/src/main/java/io/hawt/web/tomcat/TomcatLoginContextConfiguration.java
hawtio-system/src/main/java/io/hawt/web/tomcat/TomcatUserDatabaseLoginContext.java

Fix for issue #1899
Added a system property which controls the algorithm used to check tomcat passwords.

ISSUE-1899 Configuration option to specify tomcat digest

---

pom.xml

Hi,
This PR upgrades Jackson to version 2.5.4, actually the same of Fabric8 project.
Andrea

Upgrade jackson to version 2.5.4 as fabric8

---

pom.xml

Hi,
This PR upgrades commons-codec to version 1.10.
Andrea

Upgrade commons-codec to version 1.10

---

pom.xml

Hi,
This PR upgrade Pax url to version 2.4.1.
Andrea

Upgrade Ops4j Pax url to version 2.4.1

---

pom.xml

Hi,
This PR upgrade Jline to version 2.12.1
Andrea

Upgrade Jline to version 2.12.1

---

pom.xml

Hi,
This PR upgrades JavaEWAH to version 1.0.2
Andrea

Upgrade JavaEWAH to version 1.0.2

---

hawtio-system/src/main/java/io/hawt/system/Authenticator.java

Added code to handle rolebased security on Jboss EAP. See #1983

---

hawtio-api-docs/package.json

Specify versions for typescript compiler in hawtio-api-docs to satisfy CI

---

hawtio-springboot/src/main/java/io/hawt/springboot/HawtioConfiguration.java

Added resourcehandler for /img/**. This commit fixes hawtio/hawtio#1985

---

hawtio-maven-indexer/src/main/java/io/hawt/maven/indexer/MavenIndexerFacade.java

setting repositories to be the correct size

---

pom.xml

Upgrade Json to version 20150729
Andrea

Upgrade Json to version 20150729

---

pom.xml

Upgrade Pax-url to version 2.4.4.
Andrea

Upgrade Pax-url to version 2.4.4

---

pom.xml

Upgrade CXF to version 3.1.4
Andrea

Upgrade Apache CXF to version 3.1.4

---

pom.xml

Switch to gitective 0.9.11 and switch back to JDK 1.7.
Andrea

Switch to gitective 0.9.11 and switch back to JDK 1.7

---

pom.xml

Upgrade Pax-url to version 2.4.5
Andrea

Upgrade Pax-url to version 2.4.5

---

pom.xml

Upgrade to latest Jackson version 2.7.0, the same used in fabric8
Andrea

Upgrade Jackson to version 2.7.0

---

hawtio-web/src/main/webapp/app/activemq/html/browseQueue.html
hawtio-web/src/main/webapp/app/camel/html/browseEndpoint.html

Hi all,
This PR is related to #2062 
Andrea

Fixes #2062 Camel plugin - Add copy button for copy message in browse endpoint 

---

pom.xml

Upgrade to latest Karaf version, 4.0.4
Andrea

Upgrade Karaf to version 4.0.4

---

hawtio-web/src/main/webapp/app/camel/js/tree.ts
hawtio-web/src/main/webapp/app/jmx/js/jmxHelpers.ts

Relates to: https://issues.jboss.org/browse/ENTESB-4350

[ENTESB-4350] Fixes #2066. Enhanced camel context tree filtering

---

docs/Plugins.md

Fix another typo

---

hawtio-system/src/main/java/io/hawt/web/LoginServlet.java

Relates to: https://issues.jboss.org/browse/ENTESB-4391

[ENTESB-4391] Handle SimplePrincipal for WildFly / EAP

---

hawtio-web/src/main/webapp/app/activemq/doc/help.md

Fix #2098 ActiveMQ - Typo in doc/help.md

---

hawtio-web/src/main/webapp/app/fabric/html/apis.html

https://issues.jboss.org/browse/ENTESB-4375

ENTESB-4375 - Fix quickstarts links in Services APIs

---

hawtio-web/src/main/webapp/app/camel/html/attributeToolBarContext.html
hawtio-web/src/main/webapp/app/camel/html/attributeToolBarRoutes.html
hawtio-web/src/main/webapp/app/camel/html/source.html
hawtio-web/src/main/webapp/app/camel/js/attributesToolBar.ts
hawtio-web/src/main/webapp/app/camel/js/camelHelpers.ts
hawtio-web/src/main/webapp/app/camel/js/source.ts
hawtio-web/src/main/webapp/app/core/js/workspace.ts
hawtio-web/src/main/webapp/app/karaf/html/features.html
hawtio-web/src/main/webapp/app/osgi/html/bundles.html

https://issues.jboss.org/browse/ENTESB-4892

ENTESB-4892 - "viewer" has some rights unexpected in hawtio

---

hawtio-web/src/main/webapp/app/ui/js/autoDropDown.ts

See: https://issues.jboss.org/browse/ENTESB-4365

ENTESB-4365 - Unnecessary down arrow

---

hawtio-web/src/main/webapp/app/activemq/html/createDestination.html
hawtio-web/src/main/webapp/app/activemq/html/createQueue.html
hawtio-web/src/main/webapp/app/activemq/html/createTopic.html
hawtio-web/src/main/webapp/app/activemq/js/destination.ts

See:
https://issues.jboss.org/browse/ENTESB-4080
https://issues.jboss.org/browse/ENTMQ-1078

ENTESB-4080 - Can't delete queue created in Hawtio when name contains ":"

---

hawtio-web/src/main/webapp/app/activemq/html/deleteTopic.html

See: https://issues.jboss.org/browse/ENTESB-5209

ENTESB-5209 - Deleting topics doesn't have a confirmation dialog

---

pom.xml

Upgrade JGit to version 4.3.0.201604071810-r and gitective to version 0.9.13
Andrea

Jgit gitective upgrade

---

hawtio-api-docs/pom.xml
hawtio-api-docs/run_node.cmd
hawtio-api-docs/run_typedoc.cmd
hawtio-git/pom.xml

Needed changes to make the build on windows to work.
Includes the following:
1. Workaround for running typedoc on windows for documentation generation.
2. Disabled some git test for windows even for development build.

Windows build

---

hawtio-web/src/main/webapp/app/core/html/preferences.html
hawtio-web/src/main/webapp/index.html

#2158 change title by data-title to avoid tooltip issue

---

hawtio-web/src/main/webapp/app/camel/html/fabricDiagram.html
hawtio-web/src/main/webapp/app/fabric/html/apis.html
hawtio-web/src/main/webapp/app/fabric/html/containerView.html
hawtio-web/src/main/webapp/app/fabric/html/containers.html

#2148: Improve RBAC for Fabric plugin

---

hawtio-system/pom.xml
hawtio-system/src/main/java/io/hawt/web/ContextFormatterServlet.java
hawtio-system/src/main/java/io/hawt/web/ExportContextServlet.java
hawtio-system/src/main/java/io/hawt/web/OpenShiftProtocolSocketFactory.java
hawtio-web/src/test/java/io/hawt/web/JBossPostApp.java
pom.xml

the commons-http stuff is eol in place of httpcomponents which needs an update
not sure on the usage of OpenShiftProtocolSocketFactory - maybe that class can be whacked

update to httpclient 4.5.1 and remove old commons-httpclient dep

---

hawtio-web/src/main/webapp/app/camel/js/routes.ts

Fix issue-2173

---

hawtio-system/src/main/java/io/hawt/web/AuthenticationFilter.java

https://issues.jboss.org/browse/ENTESB-5891

ENTESB-5891 - Viewer has admin rights after connecting to another Fuse

---

hawtio-web/src/main/webapp/app/jvm/js/connect.ts

Updated auto-connect feature by adding ability to choose connection scheme.

Addresses ticket #1965,  connection scheme setting update

---

hawtio-web/src/main/webapp/app/osgi/html/pid-details.html
hawtio-web/src/main/webapp/app/wiki/js/wikiTopLevel.ts

Found while fixing https://issues.jboss.org/browse/ENTESB-5970

#2148: RBAC for Fabric - Wiki - configuration buttons

---

hawtio-web/src/main/webapp/app/fabric/html/brokers.html

Found while fixing https://issues.jboss.org/browse/ENTESB-5971

#2148: RBAC for Fabric - Services - MQ links

---

pom.xml

Needed for https://github.com/rhuss/jolokia/pull/283

Upgrade jolokia to support streams in servlets

---

hawtio-web/src/main/d.ts/keycloak.d.ts

Updated KeyCloak type definitions based on manual: https://keycloak.gitbooks.io/securing-client-applications-guide/content/topics/oidc/javascript-adapter.html

Updated keycloak type definitions

---

CHANGES.md

I'm proposing this to be added to the changes list because it is visually impacting a big majority of the app (thus most of the users)

Listing the fix for page flickering

---

hawtio-karaf-terminal/pom.xml
hawtio-karaf-terminal/src/main/java/io/hawt/web/plugin/karaf/terminal/JLineTerminal.java
hawtio-karaf-terminal/src/main/java/io/hawt/web/plugin/karaf/terminal/KarafConsoleFactory.java
hawtio-karaf-terminal/src/main/java/io/hawt/web/plugin/karaf/terminal/TerminalServlet.java
hawtio-karaf-terminal/src/main/java/io/hawt/web/plugin/karaf/terminal/WebTerminal.java
hawtio-karaf-terminal/src/main/java/io/hawt/web/plugin/karaf/terminal/karaf4/Karaf4ConsoleFactory.java
pom.xml

This does not keep hawtio terminal compatible with earlier karaf versions.

#2028 Migrated karaf terminal plugin to work on karaf 4.x

---

hawtio-base/src/main/webapp/WEB-INF/web.xml
hawtio-web/src/main/webapp/WEB-INF/web.xml
hawtio-wildfly/src/main/webapp/WEB-INF/web.xml

https://issues.jboss.org/browse/ENTESB-6419

Apply token-based Keycloak integration to hawtio-base & hawtio-wildfly

---

.editorconfig
hawtio-fabric8-branding/src/main/webapp/index.html
hawtio-karaf-terminal/src/main/webapp/index.html
hawtio-plugin-examples/custom-perspective/readme.md
hawtio-plugin-examples/custom-perspective/src/main/webapp/index.html
hawtio-plugin-examples/groovy-shell-plugin/src/main/webapp/index.html
hawtio-plugin-examples/irc-client-plugin/src/main/webapp/index.html
hawtio-plugin-examples/simple-plugin/src/main/webapp/index.html
hawtio-plugin-examples/social-plugin/src/main/webapp/index.html
hawtio-redhat-amq-branding/pom.xml
hawtio-redhat-amq-branding/src/main/webapp/index.html
hawtio-redhat-fuse-branding/src/main/webapp/index.html

https://issues.jboss.org/browse/ENTESB-5892

ENTESB-5892 - Jetty - Applications: Links in the list are wrong

---

hawtio-web/src/main/webapp/app/diagnostics/css/diagnostics.css
hawtio-web/src/main/webapp/app/diagnostics/doc/help.md
hawtio-web/src/main/webapp/app/diagnostics/html/flags.html
hawtio-web/src/main/webapp/app/diagnostics/html/heap.html
hawtio-web/src/main/webapp/app/diagnostics/html/jfr.html
hawtio-web/src/main/webapp/app/diagnostics/html/layoutDiagnostics.html
hawtio-web/src/main/webapp/app/diagnostics/js/diagnosticHelpers.ts
hawtio-web/src/main/webapp/app/diagnostics/js/diagnosticsPlugin.ts
hawtio-web/src/main/webapp/app/diagnostics/js/flags.ts
hawtio-web/src/main/webapp/app/diagnostics/js/heap.ts
hawtio-web/src/main/webapp/app/diagnostics/js/jfr.ts
hawtio-web/src/main/webapp/app/diagnostics/js/navbar.ts
hawtio-web/src/test/specs/spec-ts/DiagnosticHelpersSpec.ts

Diagnostic plugin
* Flight recorder - control jfr from hawtio
* Class Histogram - obtain and parse class histogram + calculate diff from previous run
* JVM flags - Show and edit JVM diagnostic flags

Plugin proposal: Diagnostics: DiagnosticCommand + HotSpotDiagnostic

---

hawtio-system/src/main/java/io/hawt/web/keycloak/KeycloakServlet.java

Keycloak - support URLHandlers

---

hawtio-web/src/main/webapp/app/diagnostics/js/flags.ts
hawtio-web/src/main/webapp/app/diagnostics/js/heap.ts

types. 
Remove redundant code.
+Ensure that edited flags are updated in GUI.

Diagnostics (Class histogram) : #2318 : use POST to get class histogram. Fix parsing of Array member

---

hawtio-system/src/main/java/io/hawt/web/keycloak/KeycloakServlet.java

Keyacloak config - supports no protocol files

---

hawtio-web/src/main/webapp/app/diagnostics/js/jfr.ts

Issue2338 - Flight recorder fixes

---

docs/Plugins.md
hawtio-web/src/main/webapp/app/runtime/doc/help.md
hawtio-web/src/main/webapp/app/runtime/js/runtimePlugin.ts
website/src/plugins/runtime/index.page

Add help / doc for runtime plugin

Document runtime

---

hawtio-web/src/main/webapp/app/diagnostics/html/jfr.html
hawtio-web/src/main/webapp/app/diagnostics/js/jfr.ts

Deals with issue #2353 . 
If recording is stopped the user has to dump and stop it before another recording can be started:

Handle stopped recordings (result of time limited recording)

---

hawtio-web/src/main/webapp/app/activemq/js/tree.ts

AMQ - protect from null error

---

hawtio-sample-springboot/README.md

Include details about configuring alternative context paths and provide
sample URLs.

Improve README for the Spring Boot sample

---

hawtio-web/src/main/webapp/lib/camelModel.js
pom.xml

Bump to Camel 2.21.1

---

hawtio-system/src/main/java/io/hawt/web/tomcat/TomcatUserDatabaseLoginContext.java

Fix NullPointerException if hawtio.tomcatUserFileLocation is not overridden

Fixes #2544 Fix NullPointerException 

---

hawtio-system/src/main/java/io/hawt/web/filters/ContentSecurityPolicyFilter.java

Fixes #2562 
@grgrzybek @alexkieling Please review this pull req.

fix(hawtio-system): fix CSP directives blocking access to keycloak

---

CHANGES.md
bom/pom.xml
hawtio-base/src/main/webapp/WEB-INF/web.xml
hawtio-console-assembly/app/src/app.ts
hawtio-embedded/src/main/java/io/hawt/embedded/Main.java
hawtio-local-jvm-mbean/pom.xml
hawtio-plugin-mbean/pom.xml
hawtio-plugin-mbean/src/main/java/io/hawt/web/plugin/HawtioPlugin.java
hawtio-plugin-mbean/src/main/java/io/hawt/web/plugin/HawtioPluginMBean.java
hawtio-plugin-mbean/src/main/java/io/hawt/web/plugin/Plugin.java
hawtio-plugin-mbean/src/test/java/io/hawt/web/plugin/HawtioPluginTest.java
hawtio-system/src/main/java/io/hawt/jmx/JmxTreeWatcher.java
hawtio-system/src/main/java/io/hawt/jmx/PluginRegistry.java
hawtio-system/src/main/java/io/hawt/web/plugin/PluginServlet.java
hawtio-war/src/main/webapp/WEB-INF/web.xml
platforms/springboot/src/main/java/io/hawt/springboot/HawtPlugin.java
platforms/springboot/src/main/java/io/hawt/springboot/HawtioManagementConfiguration.java
platforms/wildfly/src/main/webapp/WEB-INF/web.xml
pom.xml

feat(plugin): restore dynamic custom plugin loading

---

examples/branding-plugin/README.md
examples/branding-plugin/pom.xml
examples/branding-plugin/src/main/java/io/hawt/example/branding/PluginContextListener.java
examples/branding-plugin/src/main/resources/WEB-INF/web.xml
examples/branding-plugin/src/main/resources/log4j.properties
examples/branding-plugin/src/main/webapp/index.html
examples/branding-plugin/src/main/webapp/plugin/brandingPlugin.js
hawtio-console-assembly/app/src/login/login.component.ts
hawtio-console-assembly/app/yarn.lock
hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationConfiguration.java
pom.xml

See https://issues.jboss.org/browse/ENTESB-12162
This opens `/plugin` as an unsecure path so custom plugins can be loaded before authentication. It also adds a plugin example that demonstrates how you can customise `hawtconfig.json` through it.

feat(plugin): ENTESB-12162 - Provide users with a better way to customise hawtconfig.json

---

hawtio-base/src/main/java/io/hawt/blueprint/HawtioBlueprintContextListener.java

Processing System Properties thread safely.

---

bom/pom.xml
examples/springboot-keycloak/pom.xml
examples/springboot-keycloak/src/main/resources/application.properties
platforms/springboot-keycloak/pom.xml
platforms/springboot-keycloak/src/main/java/io/hawt/springboot/keycloak/HawtioKeycloakConfiguration.java
platforms/springboot-keycloak/src/main/java/io/hawt/springboot/keycloak/KeycloakConfigResolverConfiguration.java
platforms/springboot-keycloak/src/main/resources/META-INF/spring.factories
platforms/springboot-keycloak/src/main/resources/io/hawt/springboot/keycloak/application.properties
platforms/springboot/pom.xml
pom.xml

feat(hawtio-springboot): ENTESB-12346 - move reusable configs from examples into hawtio-springboot-keycloak

---

hawtio-console-assembly/app/package.json
hawtio-console-assembly/app/yarn.lock

@tadayosi update for hawtio-integration with latest JMX HTML view changes. Please take a look

feat update hawtio-integration

---

pom.xml

Upgrade Apache HTTP Components HttpClient to 4.5.13

---

hawtio-system/src/main/java/io/hawt/web/filters/FlightRecordingDownloadFacade.java

Managed to break support for local jolokia servlet in last change for proxy.
Now works for both.
@tadayosi Apologies for managing to miss this in #2669

Support for proxy servlet broke jolokia. Fix tested in both scenarios

---

pom.xml

Upgrade Google Guava to 30.1-jre

---

pom.xml

Upgrade commons-io:commons-io to 2.8.0

---

README.md

Partly resolved issue https://github.com/hawtio/hawtio/issues/2638

docs: partially resolved #2638

---

hawtio-log-logback/pom.xml
hawtio-log-logback/src/main/java/io/hawt/log/logback/LogbackLogQuery.java
hawtio-log-logback/src/main/java/io/hawt/log/logback/LogbackLogQueryMBean.java
hawtio-log-logback/src/main/java/io/hawt/log/logback/LoggingEventMapper.java
hawtio-log-logback/src/test/java/io/hawt/log/logback/LogbackLogQueryTest.java
hawtio-log/src/main/java/io/hawt/log/LogEvent.java
hawtio-log/src/main/java/io/hawt/log/support/LogQueryBase.java
hawtio-log/src/main/java/io/hawt/log/support/LogQuerySupport.java
hawtio-log/src/main/java/io/hawt/log/support/LruList.java
hawtio-log/src/main/java/io/hawt/log/support/MavenCoordHelper.java
hawtio-log/src/main/java/io/hawt/log/support/Objects.java
hawtio-log/src/main/java/io/hawt/log/support/ThrowableFormatter.java
platforms/springboot/pom.xml
platforms/springboot/src/main/java/io/hawt/springboot/SpringHawtioContextListener.java
pom.xml

feat(springboot): ENTESB-18661 implement LogQueryMBean for Logback/Spring Boot

---

pom.xml

Upgrade json from 20171018 to 20180130 for vulnerability fix:
- [MPS-2022-13520](https://www.oscs1024.com/hd/MPS-2022-13520)

fix(sec): upgrade json to 20180130

---

tests/springboot/src/test/java/io/hawt/tests/spring/boot/runners/RunSpringBootCamelTest.java
tests/springboot/src/test/java/io/hawt/tests/spring/boot/runners/RunSpringBootDevTest.java
tests/springboot/src/test/java/io/hawt/tests/spring/boot/runners/RunSpringBootSmokeTest.java
tests/springboot/src/test/resources/features/about/about_modal_window.feature
tests/springboot/src/test/resources/features/camel/components/camel_components.feature
tests/springboot/src/test/resources/features/camel/components/camel_specific_component.feature
tests/springboot/src/test/resources/features/camel/contexts/camel_contexts.feature
tests/springboot/src/test/resources/features/camel/contexts/camel_specific_context.feature
tests/springboot/src/test/resources/features/camel/tree/camel_tree.feature
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/Table.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/CamelTree.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/dialog/CamelAttributeDetailDialog.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelAttributes.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelChart.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelOperations.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelProperties.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelTypeConverters.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/CamelPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/components/CamelComponentsPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/components/CamelSpecificComponentPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/contexts/CamelContextsPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/contexts/CamelSpecificContextPage.java
tests/utils/src/main/java/io/hawt/tests/utils/setup/WebDriver.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/CamelCommonStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/components/CamelComponentsStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/components/CamelSpecificComponentStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/contexts/CamelContextsStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/contexts/CamelSpecificContextStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/tree/CamelTreeStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/menu/LeftSideMenuStepDefs.java

This PR includes sample tests for Camel Context and Components, and also includes page objects with fragments and step definitions which will used by other tests in upcoming PRs.

[E2E Tests] Camel Context and Component tests

---

tests/springboot/src/test/resources/features/camel/endpoints/camel_endpoints.feature
tests/springboot/src/test/resources/features/camel/endpoints/camel_specific_endpoint.feature
tests/springboot/src/test/resources/features/camel/routes/camel_routes.feature
tests/springboot/src/test/resources/features/camel/routes/camel_specific_route.feature
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/dialog/CamelMessageForwardDialog.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelAttributes.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelChart.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelChartEdit.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelProperties.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/endpoints/CamelBrowse.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/endpoints/CamelEndpoints.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/endpoints/CamelEndpointsAdd.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/endpoints/CamelSend.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/routes/CamelDebug.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/routes/CamelRouteDiagram.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/routes/CamelRoutes.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/components/CamelComponentsPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/components/CamelSpecificComponentPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/endpoints/CamelEndpointsPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/endpoints/CamelSpecificEndpointPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/routes/CamelRoutesPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/routes/CamelSpecificRoutePage.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/CamelCommonStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/components/CamelSpecificComponentStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/endpoints/CamelEndpointsStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/endpoints/CamelSpecificEndpointStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/routes/CamelRoutesStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/camel/routes/CamelSpecificRouteStepDefs.java

Adding E2E tests covering Camel Endpoints and Routes

[E2E Tests] Camel Endpoints and Routes tests

---

tests/springboot/src/test/resources/features/quartz/quartz_jobs.feature
tests/springboot/src/test/resources/features/quartz/quartz_scheduler.feature
tests/springboot/src/test/resources/features/quartz/quartz_triggers.feature
tests/utils/pom.xml
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/Filter.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/SortedTable.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/Table.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/menu/Menu.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/quartz/QuartzTree.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/quartz/dialog/QuartzJobDataMapDetailDialog.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/quartz/tabs/QuartzJobs.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/quartz/tabs/QuartzScheduler.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/quartz/tabs/QuartzTriggers.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/HawtioPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/camel/CamelPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/quartz/QuartzPage.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/quartz/QuartzSpecificSchedulerPage.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/common/TableStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/menu/LeftSideMenuStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/quartz/QuartzStepDefs.java

Presenting set of tests for Quartz tab and its functionality.

Hawtio e2e quartz tests

---

tests/pom.xml

Update test frameworks dependencies

[E2E tests] Update test frameworks dependencies

---

tests/springboot/src/test/resources/features/quartz/quartz_jobs.feature
tests/springboot/src/test/resources/features/runtime/runtime_metrics.feature
tests/springboot/src/test/resources/features/runtime/runtime_system_properties.feature
tests/springboot/src/test/resources/features/runtime/runtime_threads.feature
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/Table.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/menu/Menu.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/runtime/dialog/RuntimeThreadDetailDialog.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/runtime/tabs/RuntimeMetrics.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/runtime/tabs/RuntimeSystemProperties.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/runtime/tabs/RuntimeThreads.java
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/pages/runtime/RuntimePage.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/common/TableStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/menu/LeftSideMenuStepDefs.java
tests/utils/src/main/java/io/hawt/tests/utils/stepdefinitions/runtime/RuntimeStepDefs.java

Basic UI tests (table and data viewing, sorting and filtering) for Runtime page and tabs.

[E2E Tests] Runtime tab tests

---

.github/workflows/e2e_test.yml
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/Panel.java
tests/utils/src/main/java/io/hawt/tests/utils/setup/LoginLogout.java

- Fixed git actions file - now e2e tests are triggered correctly
- Added a new parameter to have less verbose logs (hide downloading messages)

[E2E Tests] Fix git actions

---

tests/quarkus/pom.xml
tests/quarkus/src/test/resources/features/camel/components/camel_specific_component.feature
tests/quarkus/src/test/resources/features/camel/contexts/camel_contexts.feature
tests/quarkus/src/test/resources/features/camel/contexts/camel_specific_context.feature
tests/quarkus/src/test/resources/features/camel/endpoints/camel_endpoints.feature
tests/quarkus/src/test/resources/features/camel/endpoints/camel_specific_endpoint.feature
tests/quarkus/src/test/resources/features/camel/routes/camel_routes.feature
tests/quarkus/src/test/resources/features/camel/routes/camel_specific_route.feature
tests/quarkus/src/test/resources/features/panel/about/about_modal_window.feature
tests/quarkus/src/test/resources/features/plugin/plugin.feature
tests/utils/src/main/java/io/hawt/tests/utils/pageobjects/fragments/camel/tabs/common/CamelOperations.java

In this PR:
- Extended test coverage for Quarkus
- Added camel timer dependency for Quarkus for testing purpose
- Stabilised one test method of execution and checking operations in Camel

[E2E Tests] Quarkus test coverage extension

---

.github/workflows/e2e_test.yml
pom.xml

chore: upgrade json-java

---

console/package.json
console/yarn.lock
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock

This fixes E2E test failures explained at #2851.
@jsolovjo

feat(console,examples): update @hawtio/react to 0.3.0-dev.4

---

deploy/hawtio-embedded/src/main/java/io/hawt/embedded/Main.java
examples/springboot-authentication-jar/pom.xml
examples/springboot-authentication-jar/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
examples/springboot-authentication/pom.xml
examples/springboot-authentication/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
pom.xml

hawtio embedded - tested successfully with jetty upgrade via jbang
spring-boot-authentication and spring-boot-authentication-jar examples works as expected, but the following exception `java.security.PrivilegedActionException: null`  is thrown, maybe related to https://access.redhat.com/solutions/7000121?

Upgrade to jetty 10

---

pom.xml

* Fixes vulnerability to CVE-2023-2976
Fixes #2892

fix(CVE): Upgrades guava

---

deploy/hawtio-embedded/pom.xml
deploy/hawtio-embedded/src/main/assembly/assembly.xml
deploy/hawtio-embedded/src/main/java/io/hawt/embedded/Main.java

Remove warning from slf4j, and print version with `hawtio --version`.

hawtio-jbang - print version

---

examples/springboot-authentication-jar/pom.xml
examples/springboot-authentication-jar/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
examples/springboot-authentication-jar/src/main/java/io/hawt/example/spring/boot/SampleAuthenticationSpringBootService.java
examples/springboot-authentication/README.md
examples/springboot-authentication/pom.xml
examples/springboot-authentication/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
examples/springboot-authentication/src/main/java/io/hawt/example/spring/boot/SampleAuthenticationSpringBootService.java
examples/springboot-authentication/src/main/webapp/hawtconfig.json
examples/springboot-log4j2/pom.xml
examples/springboot-log4j2/src/main/java/io/hawt/example/spring/boot/SampleSpringBootService.java
examples/springboot/pom.xml
examples/springboot/src/main/java/io/hawt/example/spring/boot/SampleSpringBootService.java
hawtio-system/pom.xml
hawtio-system/src/main/java/io/hawt/system/Authenticator.java
platforms/springboot/pom.xml
pom.xml

Migrate springboot-authentication example.
related #2819

Refactor(examples): upgrade springboot-authentication example to sb3 and jetty 12.0.0.beta4

---

platforms/springboot-keycloak/pom.xml
platforms/springboot-keycloak/src/main/java/io/hawt/springboot/keycloak/HawtioKeycloakConfiguration.java

Fix #2923
@mmuzikar Please review this.

fix(keycloak): custom UI resources are blocked when using Keycloak with Spring Boot #2923

---

examples/quarkus-keycloak/src/main/java/io/hawt/example/quarkus/SampleCamelRoute.java
examples/quarkus/src/main/java/io/hawt/example/quarkus/SampleCamelRoute.java
platforms/quarkus/deployment/src/main/java/io/hawt/quarkus/deployment/HawtioProcessor.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/HawtioProducers.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/auth/HawtioQuarkusAuthenticator.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/filters/HawtioQuarkusAuthenticationFilter.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/filters/HawtioQuarkusLoginRedirectFilter.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/filters/HawtioQuarkusPathFilter.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/servlets/HawtioQuakusLoginServlet.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/servlets/HawtioQuakusLogoutServlet.java
pom.xml

Migration to quarkus 3.1.1 and jakarta ee within quarkus platform and quickstarts modules. Quarkus quickstart is also working.

feat: Migrate to quarkus 3.1.1

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelChart.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelOperations.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/routes/CamelDebug.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/HawtioPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/CamelChartStepDefs.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/CommonCamelStepDefs.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/routes/CamelRoutesStepDefs.java
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/contexts/camel_specific_context.feature
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/routes/camel_specific_route.feature
tests/quarkus/src/main/java/io/hawt/tests/quarkus/SampleCamelRoute.java

In this PR added:
- Camel Routes Chart test scenario
- Camel Routes basic tests in Debug tab
- Minor fixes and stabilizations

[E2E Tests] Add Camel Routes Chart and Debug tests

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/CamelTree.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/CamelTreeStepDefs.java
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/tree/camel_tree.feature

In this PR:
- New scenarios to expand, collapse and filter the Camel tree

[E2E Tests] Camel tree tests

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/Tree.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/camel/CamelPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/jmx/JmxPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/CamelTreeStepDefs.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/jmx/JmxTreeStepDefs.java
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/jmx/tree/jmx_tree.feature

In this PR:
- CamelTree class was refactored, now it's Tree class and reused both in Camel tree and JMX tree;
- Basic tests checking JMX tree;
- A new JmxPage was added which is preparation for upcoming JMX tests

[E2E Tests] Refactor tree and add jmx tree tests

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/hooks/LoginLogoutHooks.java
tests/pom.xml

In this PR:
- Update test frameworks versions
- Optimise LoginLogoutHooks class (it was failing during the test project build)

[E2E Tests] Update test framework versions

---

examples/quarkus/pom.xml
tests/quarkus/pom.xml

Apply workaround for apache/camel-quarkus#5407

fix(e2e): apply workaround to fix Quarkus E2E temporarily

---

tests/pom.xml

This PR contains test framework version updates and should fix the issue https://github.com/hawtio/hawtio/pull/2955

[E2E Tests] Upgrade test frameworks

---

hawtio-system/pom.xml
plugins/hawtio-local-jvm-mbean/pom.xml
pom.xml

fix(system): update Jolokia to 2.0.0-M4

---

console/yarn.lock
hawtio-system/src/main/java/io/hawt/jmx/RBACRegistry.java
hawtio-system/src/main/java/io/hawt/jmx/RBACRegistryMBean.java
hawtio-system/src/test/java/io/hawt/jmx/RBACRegistryTest.java

feat(system): return partial list of MBeans based on path from RBACRegistry#list()

---

console/craco.config.js
console/package.json
console/yarn.lock
deploy/hawtio-default/pom.xml
deploy/hawtio-default/src/main/java/io/hawt/HawtioDefaultContextListener.java
deploy/hawtio-default/src/main/webapp/WEB-INF/web.xml
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock
plugins/hawtio-local-jvm-mbean/src/main/java/io/hawt/jvm/local/JVMList.java

Applies the new feature from hawtio/hawtio-next#656

feat(console): apply Connect Discover tab

---

console/craco.config.js
console/package.json
console/yarn.lock
deploy/hawtio-default/pom.xml
deploy/hawtio-default/src/main/java/io/hawt/HawtioDefaultContextListener.java
deploy/hawtio-default/src/main/webapp/WEB-INF/web.xml
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock
plugins/hawtio-local-jvm-mbean/src/main/java/io/hawt/jvm/local/JVMList.java

Applies the new feature from hawtio/hawtio-next#656

feat(console): apply Connect Discover tab (3.x)

---

hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationFilter.java
hawtio-system/src/main/java/io/hawt/web/auth/LoginServlet.java
hawtio-system/src/main/java/io/hawt/web/auth/UserServlet.java

fix(system): stabilise Spring Security authentication

---

hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationFilter.java
hawtio-system/src/main/java/io/hawt/web/auth/LoginServlet.java
hawtio-system/src/main/java/io/hawt/web/auth/UserServlet.java

fix(system): stabilise Spring Security authentication (3.x)

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/endpoints/CamelEndpointsAdd.java

In this PR:
- Fix Add an endpoint from Data test scenario which started failing in https://github.com/hawtio/hawtio-next/pull/695

[E2E Tests] Fix add endpoint from Data test

---

platforms/quarkus/deployment/src/main/java/io/hawt/quarkus/deployment/HawtioProcessor.java

fixes #3146
https://github.com/hawtio/hawtio/assets/12056979/fd7d25c5-5b14-4eca-902f-f285f679e950

Add a link for the Console in the Quarkus Dev UI

---

console/package.json
console/yarn.lock
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock

- It fixes issue with a war plugin not able to customise branding.

fix: update @hawtio/react to 1.0.2

---

deploy/hawtio-default/src/main/webapp/WEB-INF/web.xml
deploy/hawtio-embedded/pom.xml
deploy/hawtio-embedded/src/main/java/io/hawt/embedded/Main.java
examples/springboot-authentication/pom.xml
examples/springboot-authentication/src/main/java/io/hawt/example/spring/boot/PropertyFileLoginModule.java
examples/springboot-authentication/src/main/java/io/hawt/example/spring/boot/SampleAuthenticationSpringBootService.java
examples/springboot-keycloak/pom.xml
examples/springboot-log4j2/pom.xml
examples/springboot-plugin/pom.xml
examples/springboot-security/pom.xml
examples/springboot/pom.xml
examples/war-plugin/src/main/webapp/WEB-INF/web.xml
hawtio-system/src/main/java/io/hawt/jmx/JmxTreeWatcher.java
hawtio-system/src/main/java/io/hawt/jmx/PluginRegistry.java
hawtio-system/src/main/java/io/hawt/web/auth/LoginServlet.java
hawtio-system/src/main/java/io/hawt/web/auth/UserServlet.java
hawtio-system/src/main/java/io/hawt/web/auth/keycloak/KeycloakServlet.java
hawtio-system/src/main/java/io/hawt/web/plugin/PluginServlet.java
hawtio-system/src/main/java/io/hawt/web/proxy/ProxyServlet.java
hawtio-war/src/main/webapp/WEB-INF/web.xml
platforms/springboot/pom.xml
pom.xml

fix: support Java 11 for 4.x

---

platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/filters/HawtioQuarkusPathFilter.java

@mmelko I found a small issue with your previous fix. Please check.
The previous fix tried to sanitise the path for /hawtconfig.json but the path passed to loadFromHawtioStatic() is always constant thus forcing sanitising it is redundant without no real gain. We should instead clarify in the code that the path is always '/hawtconfig.json' to make the analyzer tool satisfy.
The previous fix also caused the following warning in the log:
```
Couldn't find file on location: file:///hawtconfig.json
```

fix(quarkus): fix loadFromHawtioStatic sanitisation

---

console/craco.config.js
console/package.json
console/yarn.lock
examples/sample-plugin/craco.config.js
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock

fix: update @hawtio/react to 1.0.5

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/dialog/CamelAttributeDetailDialog.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/HawtioPage.java

The fix is required by UX change https://github.com/hawtio/hawtio-next/pull/818
Added clickButtonByAriaLabel method

[E2E Tests] Fix Close Attributes modal window due to UX changes

---

pom.xml

Fix https://issues.apache.org/jira/browse/CAMEL-20598

fix(embedded): fix `camel hawtio` not launching by downgrading slf4j to 2.0.11

---

deploy/hawtio-embedded/src/main/java/io/hawt/embedded/Main.java

fix(jbang): change default host from 0.0.0.0 to localhost

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/Table.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/CamelTableStepDefs.java
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/components/camel_specific_component.feature
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/endpoints/camel_specific_endpoint.feature
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/routes/camel_specific_route.feature

- Add new tests for sortable attributes

[E2E Tests] Add sorting attributes tests

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/config/TestConfiguration.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/hooks/DeployAppHook.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/hooks/ScreenshotHook.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/openshift/HawtioOnlineUtils.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/Tree.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/about/AboutModalWindow.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelOperations.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/online/DiscoverTab.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/HawtioPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/LoginLogout.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/deployment/OpenshiftDeployment.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/panel/about/AboutModalWindowStepDefs.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/utils/Attachments.java
tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/HawtioOperatorTest.java
tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/utils/SelenideTestWatcher.java
tests/hawtio-test-suite/src/test/java/io/hawt/tests/utils/rp/RPTestExecutionListener.java
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/panel/about/about_modal_window.feature
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/openshift/acl.yaml

Adds tests for the main sections of the Hawtio CR, tests happy path coverage for basic usage of those parameters.

e2e: Add tests for hawtio-operator

---

tests/hawtio-test-suite/src/test/java/io/hawt/tests/utils/rp/RPTestExecutionListener.java

Fixes attachments to RP for Cucumber tests, before this change RP reports didn't contain the screenshot proving quite useless in terms of a report.

Fix RP attachments for Cucumber

---

examples/springboot-log4j2/pom.xml
examples/springboot/pom.xml
pom.xml
tests/pom.xml
tests/springboot/pom.xml
tests/springboot/src/main/java/io/hawt/tests/spring/boot/PropertyFileLoginModule.java
tests/springboot/src/main/java/io/hawt/tests/spring/boot/SpringBootService.java

https://issues.redhat.com/browse/HAWNG-497

fix: HAWNG-497 Update RHBOAC for Spring Boot version to 4.4.0

---

pom.xml

https://issues.redhat.com/browse/HAWNG-497

fix: HAWNG-497 Update RHBOAC for Quarkus version to 4.4.0

---

hawtio-system/src/main/java/io/hawt/web/filters/ContentSecurityPolicyFilter.java
hawtio-system/src/test/java/io/hawt/web/filters/ContentSecurityPolicyFilterTest.java

fix(CSPFilter): Tweak the CSP to get working the code editor after PF5 upgrade

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/Tree.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelChart.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/ConnectPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/HawtioPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/LoginPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/panel/help/HelpPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/plugin/PluginPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/LoginLogout.java
tests/quarkus/src/main/resources/META-INF/resources/hawtio/css/app.css
tests/springboot/src/main/resources/hawtio-static/css/app.css

- Refactor tests (fix) according to Patternfly 5 changes in https://github.com/hawtio/hawtio-next/pull/953

[E2E Tests] Refactor tests according to Patternfly 5 changes

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/Panel.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/routes/CamelRoutes.java

Refactor tests according to https://github.com/hawtio/hawtio-next/pull/960

[E2E Tests] Refactor tests according to PF5 changes for drop-downs

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/endpoints/CamelEndpointsAdd.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/endpoints/CamelSend.java

Refactor add Camel endpoint and send message tests according to changes in https://github.com/hawtio/hawtio-next/pull/981

[E2E Tests] Refactor camel endpoints and send message tests to PF5

---

console-minimal/package.json
console-minimal/yarn.lock
console/package.json
console/yarn.lock
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock

fix(HAWNG-751): Webpack upgrade

---

.github/workflows/e2e_test.yml
tests/hawtio-test-suite/process_test_results.sh

Update download and upload artifact actions and fix merging files

fix(ci-e2e): fix merging of test results

---

hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationConfiguration.java

fix(system): auth throttling should be disabled when Keycloak/OIDC is used

---

pom.xml

(cherry picked from commit ed4c8de13d88ab6f07f12f2b3f9db475abda2e87)

chore(deps): Upgrade Jolokia to 2.1.2

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/panel/help/HelpPage.java

Adjust the tests (Help page) according to the changes in https://github.com/hawtio/hawtio-next/pull/1201

[E2E] Fix tests for PR 1201

---

pom.xml

Passing those e2e tests locally:
```console
mvn install -Pe2e,e2e-springboot -am -pl :hawtio-test-suite -Dlocal-app=true
```
```console
mvn install -Pe2e,e2e-quarkus -am -pl :hawtio-test-suite -Dlocal-app=true
```

fix: HAWNG-851 Update to CSB 4.8.0.redhat-00021 / CQ 3.15.2.redhat-00002

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/Panel.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/common/CamelOperations.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/online/DiscoverTab.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/ConnectPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/openshift/HawtioOnlineLoginPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/pages/panel/help/HelpPage.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/LoginLogout.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/setup/WebDriver.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/utils/ByUtils.java
tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/ClusterDiscoveryTest.java
tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/HawtioOnlineShellTest.java
tests/hawtio-test-suite/src/test/java/io/hawt/tests/openshift/utils/BaseHawtioOnlineTest.java

Fixes around the changes in Hawtio Online 4.1, fix lockout test on hawtio online and ignore it on Hawtio Online as auth is defined by OCP

E2E: various fixes for 4.1 version

---

platforms/quarkus/deployment/src/main/java/io/hawt/quarkus/deployment/HawtioConfigCustomizer.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/HawtioProducers.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/auth/HawtioQuarkusAuthenticator.java

fix(quarkus): cannot include camel-quarkus-cxf-soap

---

console-minimal/package.json
console-minimal/yarn.lock

Revert "chore(deps-dev): bump monaco-editor from 0.52.0 to 0.52.2 in /console-minimal"

---

bom/pom.xml
console-minimal/package.json
console-minimal/yarn.lock
console/package.json
console/yarn.lock
deploy/hawtio-default/pom.xml
deploy/hawtio-default/src/main/webapp/WEB-INF/web.xml
deploy/hawtio-embedded/pom.xml
deploy/hawtio-embedded/src/main/java/io/hawt/embedded/ConnectionConverter.java
deploy/hawtio-embedded/src/main/java/io/hawt/embedded/HawtioDefaultLocator.java
deploy/hawtio-embedded/src/main/java/io/hawt/embedded/Main.java
deploy/hawtio-embedded/src/test/java/io/hawt/embedded/ConnectionConverterTest.java
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock
hawtio-system/src/main/java/io/hawt/web/auth/AuthenticationConfiguration.java
plugins/hawtio-connect/pom.xml
plugins/hawtio-connect/src/main/java/io/hawt/connect/Connection.java
plugins/hawtio-connect/src/main/java/io/hawt/connect/PresetConnectionsServlet.java
pom.xml

feat(jbang): add option to auto-connect to a remote Jolokia endpoint 

---

.github/workflows/jbang-test.yml

"Successful" run: https://github.com/mmuzikar/hawtio/actions/runs/13328810943
Will only run on push - I don't think we need to run these tests on every pull request
Closes #3798

e2e: add workflow for testing camel hawtio jbang app

---

platforms/quarkus/deployment/src/main/java/io/hawt/quarkus/deployment/HawtioProcessor.java
platforms/quarkus/runtime/src/main/java/io/hawt/quarkus/auth/SessionConfigurationServletExtension.java

@jamesnetherton may I ask you to check if I did it the right "Quarkus" way?

fix(quarkus): Set HttpOnly flag on JSESSIONID cookie for hawtio-quarkus (HAWNG-945)

---

deploy/hawtio-embedded/src/main/assembly/assembly.xml

Fix #3796
@grgrzybek This indeed fixes the issue on my local env. But could you please give a sanity check on whether it's the correct direction?

fix(embedded): fail to launch camel hawtio command

---

examples/springboot-authentication/pom.xml
examples/springboot-keycloak/pom.xml
examples/springboot-log4j2/pom.xml
examples/springboot-plugin/pom.xml
examples/springboot-security/pom.xml
examples/springboot/pom.xml
platforms/jetty-security/pom.xml
platforms/springboot-security/pom.xml
platforms/springboot/pom.xml
pom.xml

build: drop support for Java 11

---

console-minimal/package.json
console-minimal/yarn.lock
console/package.json
console/yarn.lock
examples/sample-plugin/package.json
examples/sample-plugin/yarn.lock
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/panel/help/help.feature

Accompanied with https://github.com/hawtio/hawtio-next/pull/1526

fix(e2e): HAWNG-1018 fix E2E for broken links on Help page

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/openshift/HawtioOnlineUtils.java

Related https://github.com/hawtio/hawtio/pull/3917/files
Typo I found while working on the tests

fix(tests): typo on configuration

---

tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/pageobjects/fragments/camel/tabs/routes/CamelRouteDiagram.java
tests/hawtio-test-suite/src/main/java/io/hawt/tests/features/stepdefinitions/camel/routes/CamelRoutesStepDefs.java
tests/hawtio-test-suite/src/test/resources/io/hawt/tests/features/camel/routes/camel_routes.feature

In this PR:
- Added a test to check whether route nodes overlaps/intersect;
- Added a test to check for uniqueness (no duplications);
Those tests should cover regressions such as in the https://github.com/hawtio/hawtio-next/issues/1543

[E2E] Camel Route Diagram tests to check overlaps and duplications.

---

platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusAuthenticationDisabledTest.java
platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusAuthenticationEnabledTest.java
platforms/quarkus/deployment/src/test/java/io/hawt/quarkus/deployment/test/HawtioQuarkusPluginConfigurationTest.java
tests/hawtio-test-suite/pom.xml
tests/pom.xml
tests/quarkus/pom.xml
tests/springboot/Dockerfile
tests/springboot/pom.xml

Update snapshot version in tests

[E2E] Update snapshot versions.
